name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente a desplegar (dev, stg, prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="../environments/${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="../environments/${{ github.event.inputs.environment }}.tfvars"
